USE [master]
GO

/****** Object:  Database [Librarysystem]    Script Date: 29.06.2020 22:30:47 ******/
CREATE DATABASE [Librarysystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Librarysystem', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Librarysystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Librarysystem_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Librarysystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Librarysystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Librarysystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Librarysystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Librarysystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Librarysystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Librarysystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [Librarysystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Librarysystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Librarysystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Librarysystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Librarysystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Librarysystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Librarysystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Librarysystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Librarysystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Librarysystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Librarysystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Librarysystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Librarysystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Librarysystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Librarysystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Librarysystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Librarysystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Librarysystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Librarysystem] SET  MULTI_USER 
GO

ALTER DATABASE [Librarysystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Librarysystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Librarysystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Librarysystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Librarysystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Librarysystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Librarysystem] SET  READ_WRITE 
GO

